config/routes.rb
Rails.application.routes.draw do

  resources :pics

  resources :stereos do
    resources :pics
  end

  root to: 'stereos#index'

end

app/models/pic.rb
class Pic < ActiveRecord::Base

  belongs_to :stereo

  has_attached_file :file, styles: { medium: "640x640#", thumb: "100x100#" }
  validates_attachment_content_type :file, :content_type => ["image/jpg", "image/jpeg"]

  after_save :process_stereo

  protected

  def process_stereo
    # we got all the pics, we can generate the gif now
    if stereo.pics.count == stereo.pic_count
      stereo.process!
    end
  end
end

app/models/stereo.rb
class Stereo < ActiveRecord::Base
  include Magick

  acts_as_taggable_on :tags

  has_many :pics

  validates :pic_count, presence: true
  validates :uuid, presence: true

  before_save :generate_uuid, on: :create
  before_save :set_effect, on: :create

  def process!
    if is_3d? && pic_count == 2
      generate_3d
    else
      generate_gif
    end
    # imagga tagging
    Imagga.tag(self)
  end

  def is_gif?
    effect.nil? || effect == 1
  end

  def is_3d?
    effect == 2
  end

  def path(format='gif')
    "public/stereos/#{uuid}.#{format}"
  end

  protected

  def set_effect
    self.effect ||= 1
  end

  def generate_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def generate_gif
    gif = ImageList.new
    pics.each do |pic|
      gif << Magick::Image::read(pic.file.path(:medium)).first
    end
    gif.write(path)
  end

  def generate_3d
    left  = Magick::ImageList.new(pics.first.file.path(:medium))
    right = Magick::ImageList.new(pics.second.file.path(:medium))
    st = left.stereo(right)
    st.write(path('jpg'))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  def new
    @pic = Pic.new
  end

  def create
    @pic = Pic.new(pic_params)
    @pic.stereo = Stereo.where(uuid: params[:uuid], pic_count: params[:pic_count]).first_or_create
    @pic.save!
    render json: @pic
  end

  protected

  def pic_params
    params.require(:pic).permit(:file)
  end
end

app/controllers/stereos_controller.rb
class StereosController < ApplicationController

  def create
    @stereo = Stereo.new(stereo_params)
    @stereo.save!
    render json: @stereo
  end

  def update
    @stereo = Stereo.find(params[:id])
    @stereo.process!
    render json: @stereo
  end

  def index
    if params[:tag]
      @stereos = Stereo.tagged_with(params[:tag])
    else
      @stereos = Stereo.order('id desc')
    end
    respond_to do |format|
      format.json { render json: @stereos.limit(10).to_json }
      format.html { @stereos = @stereos.limit(180) }
    end
  end

  def show
    @stereo = Stereo.find(params[:id])
    respond_to do |format|
      format.json { render json: @stereo.to_json }
      format.html
    end
  end

  protected

  def stereo_params
    params.require(:stereo).permit(:uuid, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/stereos_helper.rb
module StereosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stereogram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pics/new.html.erb
<%= form_for @pic, url: pics_path, html: { multipart: true } do |form| %>
  <%= label_tag :uuid %>
  <%= text_field_tag :uuid %><br />

  <%= label_tag :pic_count %>
  <%= text_field_tag :pic_count %><br />

  <%= label_tag :effect %>
  <%= text_field_tag :effect %><br />

  <%= form.file_field :file %>
  <%= submit_tag 'Save' %>
<% end %>

app/views/stereos/_stereo.html.erb
<div class="stereo" style="float:left;margin:0;padding:0">
  <a href="/stereos/<%= stereo.id %>"><img src="/stereos/<%= stereo.uuid %>.gif" width="200"/></a>
</div>

app/views/stereos/index.html.erb
<%= render @stereos %>

app/views/stereos/show.html.erb
<% if @tag=@stereo.tag_list.any? %>
  <h3>
  <% @stereo.tag_list.each do |tag| %>
    <%= link_to tag, stereos_path(tag: tag) %>
  <% end %>
  </h3>
<% end %>
<img src="/stereos/<%= @stereo.uuid %>.gif" width="640"/>